# Generated by Django 2.1.4 on 2019-01-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='pic_path',
            field=models.ImageField(default='/nothing', upload_to='images/'),
        ),
    ]
