# Generated by Django 2.1.5 on 2019-02-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.AddField(
            model_name='review',
            name='deal_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.Deal'),
        ),
    ]
