# Generated by Django 2.1.5 on 2019-03-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190227_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic_path',
            field=models.ImageField(default='/nothing', upload_to='login/static/images/'),
        ),
    ]
