# Generated by Django 2.1.7 on 2019-03-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190227_1600'),
        ('home', '0009_auto_20190305_2117'),
    ]

    operations = [
    ]
