# Generated by Django 2.1.7 on 2019-03-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_merge_20190306_1628'),
        ('home', '0012_auto_20190304_1141'),
    ]

    operations = [
    ]
