# Generated by Django 2.1.7 on 2019-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic_path',
            field=models.ImageField(default='/nothing', upload_to='images/'),
        ),
    ]
