# Generated by Django 2.1.5 on 2019-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190319_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic_path',
            field=models.ImageField(default='/nothing', upload_to='login/static/images/'),
        ),
    ]
