# Generated by Django 2.1.7 on 2019-03-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190319_1540'),
        ('home', '0018_auto_20190319_1547'),
    ]

    operations = [
    ]
