# Generated by Django 2.1.7 on 2019-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_merge_20190319_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic_path',
            field=models.ImageField(default='/nothing', upload_to='static/images/'),
        ),
    ]
