# Generated by Django 2.1.5 on 2019-01-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='fullname',
        ),
    ]
