# Generated by Django 2.1.4 on 2019-01-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userinfo_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='dob',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='nadiad', max_length=10),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usertype',
            field=models.CharField(default='Farmer', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mob',
            field=models.IntegerField(),
        ),
    ]
